//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherForecast.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class temprature_details
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string day { get; set; }
        public string degree { get; set; }
        public string hour { get; set; }
        public string uv { get; set; }
        public string wind { get; set; }
    }
}
